### ISSUE TITLE
Remove local Prettier config from package.json

### ISSUE THREAD

**Issue by jeddy3** [stylelint/npm-package-json-lint-config#2]
We should remove [these lines](https://github.com/stylelint/npm-package-json-lint-config/blob/8c1b78d8020df3b16569c54af7994c26adec5fc5/package.json#L47-L54):

```
	"prettier": {
		"arrowParens": "always",
		"endOfLine": "lf",
		"printWidth": 100,
		"singleQuote": true,
		"trailingComma": "all",
		"useTabs": true
	},
```

From `package.json` as this local config is overriding the shared `@stylelint/prettier-config` one, causing the `package.json`to be indented with tabs.

**Comment by ntwb** [comment]
This is why I am defining the config specifically instead of using the `@stylelint/prettier-config` configuration, npm `package.json` and 	package-lock.json` files fully supported using tabs as indentation, Prettier should also (not be adjusting the `printWidth`](https://github.com/stylelint/prettier-config/blob/master/.prettierrc.js#L14) of these files, in particular the lock file, this file should remain "machine generated" by npm and not modified by Prettier

As such, rather than changing the current indentation from tabs to spaces here in this repo to then change them back to tabs in a few days once I've worked out how to update the Prettier configuration to take into consideration all of the needed requirements is why I'm holding of on this at the moment

**Comment by jeddy3** [comment]
> npm package.json and package-lock.json files fully supported using tabs as indentation

I didn't know that. I thought `npm i` converted things to spaces regardless.

> once I've worked out how to update the Prettier configuration to take into consideration all of the needed requirements is why I'm holding of on this at the moment

👍
